version: "3.8"

services:
  app:
    container_name: app_c
    build: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    restart: always
  # sqlite3:
  #   image: sqlite3:latest
  #   container_name: db_app
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - ./backend:./app
  frontend:
    container_name: frontend_c
    build: ./frontend
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true

    
